name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If your Docker image doesn't already have deps,
      # the script will install them via requirements.txt.
      - name: Ensure script is executable (in case git perms are stripped)
        run: chmod +x dev/run_tests.sh

      - name: Run unit tests via script
        run: dev/run_tests.sh
        shell: bash
