# .github/workflows/ci.yml
name: CI
on:
  push: { branches: [main, master] }
  pull_request:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tag: ${{ steps.meta.outputs.tags }}   # we’ll pick a stable tag below
      latest: ghcr.io/${{ github.repository }}/ci:latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}/ci
          tags: |
            type=raw,value=latest
            type=sha
      - uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/dev/Dockerfile   # <- your Dockerfile path
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  test:
    runs-on: ubuntu-latest
    needs: build-image
    container:
      image: ${{ needs.build-image.outputs.latest }}  # use the just-pushed :latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4
      - name: Make test script executable
        run: chmod +x dev/run_tests.sh
      - name: Run unit tests
        run: dev/run_tests.sh
        shell: bash
