# .github/workflows/ci.yml
name: CI
on:
  push: { branches: [main, master] }
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Make sure the script is executable (in case git perms don’t preserve +x)
      - name: Make test script executable
        run: chmod +x dev/run_tests.sh

      # Run your script
      - name: Run unit tests via script
        run: dev/run_tests.sh
        shell: bash
